// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import Editora from '../editora';
import Livro from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editora: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}
  
  ngOnInit(): void {
    this.editora = this.servEditora.getEditoras();
    this.livros = this.servLivros.obterLivros();
  };

  excluir = (codigoLivro: number): void => {
    this.servLivros.excluir(codigoLivro);
    this.livros = this.servLivros.obterLivros();
  };

  obterNome(codEditora: number): string {
    return this.servEditora.getNomeEditora(codEditora) || 'Editora não encontrada';
  };

}

<main class="container">
    <h1>Catálogo de Livros</h1>
    <table class="table table-bordered table table-striped">
        <thead class="table-dark">
            <tr>
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">
                <td>{{ livro.titulo }} <br>
                    <button class="btn btn-danger" (click)="excluir(livro.codigo)">
                        Excluir
                    </button>
                </td>
                <td>{{ livro.resumo }}</td>
                <td>{{ obterNome(livro.codEditora) }}</td>
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>

// clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect} from 'react';
import ControleLivros from './controle/ControleLivros'
import ControleEditora from './controle/ControleEditora'

export const LinhaLivro = ({ livro, excluir }) => {
    const controleEditora = new ControleEditora();
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

    return (
        <tr>
            <td className='mx-2 my-3 px-3'>{livro.titulo}<br/>
                <button className='btn btn-danger' onClick={() => excluir(livro.codigo)}>Excluir</button>
            </td>
            <td className='mx-2 my-3 px-3'>{livro.resumo}</td>
            <td className='mx-2 my-3 px-3'>{nomeEditora}</td>
            <ul className='mt-2'>
                {livro.autores.map((autor, index) => (
                    <li key={index}>{autor}</li>
                ))}
            </ul>
            
        </tr>
    );
}

export default function LivroLista() {
    const [livros, setLivros] = useState ([]);
    const [carregado, setCarregado] = useState (false);

    useEffect(() => {
        if (!carregado) {
            const controladorLivros = new ControleLivros();
            const livrosCarregados = controladorLivros.obterLivros();
            setLivros(livrosCarregados);
            setCarregado(true);
        }
    }, [carregado]);

    const excluir = (codigoLivro) => {
        const controladorLivros = new ControleLivros();
        controladorLivros.excluir(codigoLivro);

        setCarregado(false);
    };

    return (
        <main className='container col-10 mt-3'>
            <h1 className='my-3'>Catálogo de Livros</h1>
            <table className='table table-striped '>
                <thead className='thead-dark'>
                    <tr>
                        <th className='col-2'>Título</th>
                        <th className='col-6'>Resumo</th>
                        <th className='col-1'>Editora</th>
                        <th className='col-1'>Autores</th>
                    </tr>
                </thead>
                <tbody>
                    {livros.map((livro) => (
                        <LinhaLivro key={livro.codigo} livro={livro} excluir={excluir} />
                    ))}
                </tbody>
            </table>
        </main>
    );
}
