// clientes/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ControleLivro from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';

const LivroDados = () => {
    const controleLivro = new ControleLivro();
    const controleEditora = new ControleEditora();
    
    const navigate = useNavigate();

    const opcoes = controleEditora.getEditoras().map((editora) => ({
        value: editora.codEditora,
        text: editora.nome,
    }));

    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(opcoes[0].value);
    
    const tratarCombo = (event) => {
        setCodEditora(Number(event.target.value));
    };

    const incluir = async () => {
        const novoLivro = {
            codigo: 0,
            titulo,
            resumo,
            autores: autores.split('/n'),
            codEditora
        };

        controleLivro.incluir(novoLivro);
        navigate('/');
    };

    return (
        <main className='container'>
            <h1>Dados do Livro</h1>
            <form className='form-group' onSubmit={incluir}>
                <div className='form-group'>
                    <label>Título</label>
                    <input className='form-control' type='text' value={titulo} onChange={(e) => setTitulo(e.target.value)}></input>
                </div>
                <div className='form-group'>
                    <label>Resumo</label>
                    <textarea className='form-control' value={resumo} onChange={(e) => setResumo(e.target.value)}></textarea>
                </div>
                <div className='form-group'>
                    <label>Editora</label>
                    <select className='form-control' value={codEditora} onChange={tratarCombo}>
                        {opcoes.map((opcao) => (
                            <option key={opcao.value} value={opcao.value}>
                                {opcao.text}
                            </option>
                        ))}
                    </select>
                </div>
                <div className='form-group'>
                    <label>Autores (1 por linha)</label>
                    <textarea className='form-control' value={autores} onChange={(e) => setAutores(e.target.value)}></textarea>
                </div>
                <button type='submit' className='btn btn-primary'>
                    Salvar Dados
                </button>
            </form>
        </main>
    );
}

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import Editora from '../editora';
import Livro from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro;
  public autoresForm: string = "";
  public editoras: Array<Editora> = [];

  constructor (
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { 
      this.livro = new Livro(1, "", "", [], 0);
   };

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split("\n");
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl("/lista")
  }
}

<main class="container col-9">
    <h1 class="mt-2">Dados do Livro</h1>
    <form (submit)="incluir()" ngNativeValidate>
        <div class="form-group mb-2">
            <label for="titulo">Título</label>
            <input type="text" name="titulo" id="titulo" class="form-control" required [(ngModel)]="livro.titulo">
        </div>
        <div class="form-group mb-2">
            <label for="resumo">Resumo</label>
            <textarea name="resumo" id="resumo" rows="3" class="form-control" [(ngModel)]="livro.resumo"></textarea>
        </div>
        <div class="form-group mb-2">
            <label for="editora">Editora</label>
            <select name="editora" id="editora" class="form-control" required [(ngModel)]="livro.codEditora">
                <option *ngFor="let editora of editoras" [value]="editora.codEditora">
                    {{ editora.nome }}
                </option>
            </select>
        </div>
        <div class="form-group mb-2">
            <label for="autores">Autores</label>
            <textarea name="autores" id="autores" rows="3" class="form-control" [(ngModel)]="autoresForm"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Salvar Dados</button>
    </form>
</main>
